### ISSUE TITLE
Is there any way to add the print details text in the four corners like on the Cura version.

### ISSUE THREAD

**Issue by greenmr** [Molodos/ElegooNeptuneThumbnails-Prusa#7]
Using this great plugin with OrcaSlicer and an Elegoo Neptune 4 Pro. I was previously using your Cura plugin and really liked the way it put print details text on the four corners. I realize things are different with a post-processor versus a plugin, but is there any way the Prusa plugin could be enhanced with this feature?

**Comment by Molodos** [comment]
Unfortunately not. Because of the fact that, when not using Cura, it is just a post processing script and not a plugin, I cannot access parameters of the Slicer, which would be needed. So I am sorry, but because of missing capabilities for such features, this will probably never work out for other slicers than Cura.
